import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree as Body, Urbanist as Heading } from "next/font/google";
import "./globals.css";

const fontBody = Body({
  variable: "--font-body",
  subsets: ["latin"],  
  weight: ["400", "500", "600", "800"],
});


const fontHeading = Heading({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["700", "800"]
});


export const metadata: Metadata = {
  title: "Fametonic",
  description: "Fametonic generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontBody.variable} ${fontHeading.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
